RSS Виртуальная клавиатура
zanchess/virtual-keyboard pull request #1
Opened 2020-04-07 06:48 UTC by zanchess

1. задание - [RSS Виртуальная клавиатура](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codejam-virtual-keyboard.md)
2. скриншот - [screenshot](https://imgur.com/a/rg4Yogw)
3. демо - [virtual keyboard](https://zanchess.github.io/virtual-keyboard/)
4. дата сдачи: 2020-04-07 / дата дедлайна: 2020-04-07
5. Total:
Maximum points - 110
Basic scope (30):
+20 - реализована генерация DOM-элементов и body в index.html пустой изначально (может находится только тег script)
+10 - нажатие на кнопку на физической клавиатуре подсвечивает кнопку на виртуальной
Standart scope (30):
+15 - есть переключение между русским и английским языком
+15 - клики мышкой по кнопкам на виртуальной клавиатуре или нажатие на кнопки физической клавиатуры, выводят символы в инпут(textarea)
Advanced scope (15):
+15 - реализована анимация нажатия на кнопку
+15 - использование в коде фишек стандарта ES6 и выше (classes, деструктуризация и т.д.)
+10 - использование eslint:
+10 - требования к репозиторию, коммитам и PR выполнены: +10
Total: 110
6.Мой комментарий:

- Инициализировал новый репозиторий (по неопытности напорол со старым). 

- Как и просил обьеденил кое какие функции в одну, но хранение данных не переделывал, потому что двойного перебора нету: когда происходить парсинг данных на клавиатуру, то у нас один перебор массива и при переборе идет обращение по ключу текущего элемента массива. Есть, правда, двойной перебор где идет сравнение аттрибутов коллекции дом элементов с нашими данными, чтобы выловить нужную кнопку на нашей виртуальной клавиатуре

2020-04-13 19:27 UTC, PokSleek requested changes

2020-04-13 19:27 UTC, PokSleek commented on index.html
> +	<link rel="stylesheet" href="./styles.css">
👍

2020-04-13 19:27 UTC, PokSleek commented on src/script.js
> +let flag = false;
naming!

2020-04-13 19:27 UTC, PokSleek commented on src/script.js
> +let currentLanguage = 'ru';
**MAGIC STRINGS** and **NUMBERS**
You should avoid any primitive strings and numbers, because:

you can do mistakes easily.
if you want to change it you have to change it every time in your code. And in big projects it's very hard to handle it.
You should create index.js or constants.js file in folder constants and put all your magic here and import it where it is needed.
For example

```
export const EN = 'en';
export const defaultLanguage = EN;
export const localStorageLanguageKey = 'lang'
...
```

2020-04-13 19:27 UTC, PokSleek commented on src/script.js
> +container.appendChild(description);
documentFragment

2020-04-13 19:27 UTC, PokSleek commented on src/script.js
> +const setCashLanguage = () => {
naming

2020-04-13 19:27 UTC, PokSleek commented on src/script.js
> +  if (currentLanguage === 'ru') {
switch

2020-04-13 19:27 UTC, PokSleek commented on src/script.js
> +  localStorage.setItem('currentLanguage', 'ru');
unused loclaStorage item

2020-04-13 19:27 UTC, PokSleek commented on src/script.js
> +      dataKeyLetters.forEach((cell) => {
optimize :)

2020-05-03 13:02 UTC, zanchess commented on src/script.js
> +  localStorage.setItem('currentLanguage', 'ru');
Is done

2020-05-03 13:02 UTC, zanchess commented on src/script.js
> +  if (currentLanguage === 'ru') {
is done

2020-05-03 13:02 UTC, zanchess commented on src/script.js
> +const setCashLanguage = () => {
is done

2020-05-03 13:02 UTC, zanchess commented on src/script.js
> +container.appendChild(description);
is done

2020-05-03 13:03 UTC, zanchess commented on src/script.js
> +let currentLanguage = 'ru';
is done

2020-05-03 13:03 UTC, zanchess commented on src/script.js
> +let flag = false;
is done

2022-12-04 16:55 UTC, merged